export enum TipoAccionAuditoria {
  CREACION = 'CREACION',
  EDICION = 'EDICION',
  CAMBIO_ROL = 'CAMBIO_ROL',
  INACTIVACION = 'INACTIVACION',
  REACTIVACION = 'REACTIVACION',
  RESET_PASSWORD = 'RESET_PASSWORD',
  VALIDACION_DOCENTE = 'VALIDACION_DOCENTE',
  EVALUACION = 'EVALUACION',
  PROPUESTA_EVALUADOR = 'PROPUESTA_EVALUADOR',
  RESPUESTA_EVALUADOR = 'RESPUESTA_EVALUADOR',
  APROBACION_EVALUADOR = 'APROBACION_EVALUADOR',
  ELIMINACION_EVALUADOR = 'ELIMINACION_EVALUADOR',
}
