export enum TipoNotificacion {
  NUEVA_SUGERENCIA = 'NUEVA_SUGERENCIA',
  RESPUESTA_SUGERENCIA = 'RESPUESTA_SUGERENCIA',
  PROPUESTA_EVALUADOR = 'PROPUESTA_EVALUADOR',
  RESULTADO_EVALUADOR = 'RESULTADO_EVALUADOR',
}
