export enum TipoNotificacion {
  NUEVA_SUGERENCIA = 'NUEVA_SUGERENCIA',
  RESPUESTA_SUGERENCIA = 'RESPUESTA_SUGERENCIA',
  PROPUESTA_EVALUADOR = 'PROPUESTA_EVALUADOR',
  RESULTADO_EVALUADOR = 'RESULTADO_EVALUADOR',
  RESULTADO_ADJUDICACION = 'RESULTADO_ADJUDICACION',
  NUEVO_COMPROBANTE = 'NUEVO_COMPROBANTE',
  COMPROBANTE_ACEPTADO = 'COMPROBANTE_ACEPTADO',
  COMPROBANTE_RECHAZADO = 'COMPROBANTE_RECHAZADO',
}
