// Catálogos estáticos usados por el seed. Se mantienen completos (las 14 unidades
// académicas y sus carreras) aunque el seed solo dé de alta usuarios y proyectos en un
// subconjunto de ellas: así se puede seguir dando de alta a mano, desde la UI, usuarios
// de cualquier otra unidad académica con su carrera correspondiente.

export const UAS_NOMBRES: string[] = [
  'Facultad de Derecho',
  'Facultad de Ciencias Económicas',
  'Facultad de Ciencias Sociales',
  'Facultad de Filosofía y Letras',
  'Facultad de Ingeniería',
  'Facultad de Medicina',
  'Facultad de Ciencias Exactas y Naturales',
  'Facultad de Arquitectura, Diseño y Urbanismo',
  'Facultad de Agronomía',
  'Facultad de Farmacia y Bioquímica',
  'Facultad de Odontología',
  'Facultad de Psicología',
  'Facultad de Ciencias Veterinarias',
  'Ciclo Básico Común (CBC)',
];

export const CARRERAS_POR_UA: Record<string, string[]> = {
  'Facultad de Derecho': ['Abogacía', 'Traductorado Público', 'Calígrafo Público'],
  'Facultad de Ciencias Económicas': [
    'Contador Público',
    'Licenciatura en Administración',
    'Licenciatura en Economía',
    'Actuario',
    'Licenciatura en Sistemas de Información de las Organizaciones',
  ],
  'Facultad de Ciencias Sociales': [
    'Licenciatura en Sociología',
    'Licenciatura en Trabajo Social',
    'Licenciatura en Relaciones del Trabajo',
    'Licenciatura en Ciencias de la Comunicación',
    'Licenciatura en Ciencia Política',
  ],
  'Facultad de Filosofía y Letras': [
    'Licenciatura en Artes',
    'Licenciatura en Ciencias Antropológicas',
    'Licenciatura en Ciencias de la Educación',
    'Licenciatura en Filosofía',
    'Licenciatura en Geografía',
    'Licenciatura en Historia',
    'Licenciatura en Letras',
    'Licenciatura en Bibliotecología y Ciencia de la Información',
    'Edición',
  ],
  'Facultad de Ingeniería': [
    'Ingeniería Civil',
    'Ingeniería en Alimentos',
    'Ingeniería en Energía Eléctrica',
    'Ingeniería Electrónica',
    'Ingeniería en Agrimensura',
    'Ingeniería en Informática',
    'Ingeniería en Petróleo',
    'Ingeniería Industrial',
    'Ingeniería Mecánica',
    'Ingeniería Naval',
    'Ingeniería Química',
    'Licenciatura en Análisis de Sistemas',
    'Bioingeniería',
  ],
  'Facultad de Medicina': [
    'Medicina',
    'Licenciatura en Enfermería',
    'Licenciatura en Fonoaudiología',
    'Licenciatura en Kinesiología y Fisiatría',
    'Licenciatura en Nutrición',
    'Licenciatura en Obstetricia',
  ],
  'Facultad de Ciencias Exactas y Naturales': [
    'Licenciatura en Ciencias Biológicas',
    'Licenciatura en Ciencias de Datos',
    'Licenciatura en Ciencias de la Atmósfera',
    'Licenciatura en Ciencias de la Computación',
    'Licenciatura en Ciencias Físicas',
    'Licenciatura en Ciencias Geológicas',
    'Licenciatura en Ciencias Matemáticas',
    'Licenciatura en Ciencias Químicas',
    'Licenciatura en Oceanografía',
    'Licenciatura en Paleontología',
    'Licenciatura en Ciencia y Tecnología de los Alimentos',
    'Licenciatura en Biotecnología',
  ],
  'Facultad de Arquitectura, Diseño y Urbanismo': [
    'Arquitectura',
    'Diseño Gráfico',
    'Diseño Industrial',
    'Diseño de Imagen y Sonido',
    'Diseño de Indumentaria',
    'Diseño Textil',
  ],
  'Facultad de Agronomía': [
    'Agronomía',
    'Licenciatura en Ciencias Ambientales',
    'Licenciatura en Economía y Administración Agrarias',
    'Licenciatura en Gestión de Agroalimentos',
  ],
  'Facultad de Farmacia y Bioquímica': [
    'Bioquímica',
    'Farmacia',
    'Licenciatura en Ciencia y Tecnología de los Alimentos',
    'Licenciatura en Biotecnología',
  ],
  'Facultad de Odontología': ['Odontología'],
  'Facultad de Psicología': ['Licenciatura en Psicología', 'Musicoterapia', 'Terapia Ocupacional'],
  'Facultad de Ciencias Veterinarias': ['Veterinaria', 'Licenciatura en Gestión de Agroalimentos'],
  'Ciclo Básico Común (CBC)': ['Ciclo Básico Común'],
};

/** Áreas docentes por unidad académica, usadas para el perfil de los docentes sembrados. */
export const AREAS_DOCENTE: Record<string, string[]> = {
  'Facultad de Derecho': ['Derecho Constitucional', 'Derecho Penal', 'Derecho Civil', 'Derecho Laboral'],
  'Facultad de Ciencias Económicas': ['Economía Aplicada', 'Administración Pública', 'Contabilidad', 'Finanzas'],
  'Facultad de Ciencias Sociales': ['Comunicación', 'Sociología', 'Trabajo Social', 'Ciencia Política'],
  'Facultad de Filosofía y Letras': ['Historia', 'Letras', 'Filosofía', 'Antropología'],
  'Facultad de Ingeniería': ['Ingeniería Civil', 'Ingeniería Electrónica', 'Ingeniería en Informática', 'Ingeniería Industrial'],
  'Facultad de Medicina': ['Clínica Médica', 'Salud Pública', 'Enfermería', 'Nutrición'],
  'Facultad de Ciencias Exactas y Naturales': ['Matemática', 'Física', 'Química', 'Computación'],
  'Facultad de Arquitectura, Diseño y Urbanismo': ['Arquitectura', 'Diseño Industrial', 'Urbanismo'],
  'Facultad de Agronomía': ['Producción Vegetal', 'Ambiente', 'Agroalimentos'],
  'Facultad de Farmacia y Bioquímica': ['Farmacología', 'Bioquímica Clínica', 'Biotecnología'],
  'Facultad de Odontología': ['Odontología', 'Salud Bucal Comunitaria'],
  'Facultad de Psicología': ['Psicología Clínica', 'Psicología Social', 'Musicoterapia'],
  'Facultad de Ciencias Veterinarias': ['Medicina Veterinaria', 'Salud Animal', 'Gestión de Agroalimentos'],
  'Ciclo Básico Común (CBC)': ['Ciencias Exactas', 'Ciencias Sociales', 'Humanidades'],
};
